[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.20'
remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]
evm_version = 'cancun'

[profile.zksync]
src = 'src'
out = 'out'
libs = ['lib']
solc = '0.8.20'
zksync = true
eraVM = true

[profile.verifier]
verifier = "zksync"
verifier_url = "${VERIFICATION_URL}" 